version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  homebanking:
    image: homebanking:2.0
    ports:
      - "8086:8086"
    links:
      - rabbitmq
